# Generated by Django 4.2.6 on 2023-10-14 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='yellowm',
            name='business_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yellow.category'),
        ),
    ]
